name: Evilthyeggman scheduled this

on:
  workflow_dispatch:
  # Uncomment these lines to test scheduled workflow notifications
  #schedule:
  # - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the job
        run: exit 1
